namespace: staging
instance: staging-user-service

replicaCount: 3

image:
  repository: ghcr.io/keremar/todo-app-user-service
  tag: df1d130-v2.0-staging

database:
  storageClassName: longhorn-storageclass
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
