{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.database.name }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Values.instance }}
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: {{ .Values.managedBy }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: {{ .Values.database.name }}
{{- end }}
