admin:
  existingSecret: grafana-admin-secret
  userKey: admin-user
  passwordKey: admin-password

service:
  type: ClusterIP

persistence:
  enabled: true
  existingClaim: grafana-data

securityContext:
  runAsNonRoot: true
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    searchNamespace: observability
    folder: /tmp/dashboards
    folderAnnotation: grafana_folder
    provider:
      foldersFromFilesStructure: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.observability.svc.cluster.local:80
        isDefault: true
        editable: false
        jsonData:
          exemplarTraceIdDestinations:
            - name: trace_id
              datasourceUid: jaeger
      - name: Jaeger
        uid: jaeger
        type: jaeger
        access: proxy
        url: http://jaeger.observability.svc.cluster.local:16686
        editable: false
      - name: Pyroscope
        uid: pyroscope
        type: grafana-pyroscope-datasource
        access: proxy
        url: http://pyroscope.observability.svc.cluster.local:4040
        editable: false
        jsonData:
          minStep: 15s

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
