---
# Source: user-service/templates/analysistemplate.yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: check-user-service-readiness
  namespace: staging
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/instance: staging-user-service
    app.kubernetes.io/managed-by: plain-manifests
spec:
  args:
  - name: service-name
  - name: port
  
  metrics:
  - name: health-check
    interval: 5s
    count: 3
    successCondition: result == "healthy"
    failureLimit: 2
    provider:
      web:
        url: "http://{{args.service-name}}.staging.svc.cluster.local:{{args.port}}/health"
        timeoutSeconds: 5
        jsonPath: "{$.status}"
