architecture: standalone

auth:
  username: sonarqube
  database: sonarqube
  existingSecret: sonarqube-db-secret
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password

primary:
  persistence:
    enabled: true
    existingClaim: sonarqube-postgresql-pvc

  resourcesPreset: none
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

volumePermissions:
  enabled: true
