architecture: standalone

auth:
  username: dtrack
  database: dtrack
  existingSecret: dtrack-db-secret
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password

primary:
  persistence:
    enabled: true
    existingClaim: dependency-track-postgresql-pvc

  resourcesPreset: none
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

volumePermissions:
  enabled: true
