apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dependency-track-postgresql-pvc
  namespace: dependency-track
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-storageclass
