apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn-storageclass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-tools-cache-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-storageclass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-npm-cache-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-storageclass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-trivy-cache-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-storageclass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-sonar-cache-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-storageclass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-docker-cache-user-service-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-storageclass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-docker-cache-todo-service-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-storageclass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-docker-cache-frontend-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-storageclass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-venv-cache-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-storageclass
