apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn-jenkins-single
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-tools-cache-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-jenkins-single
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-npm-cache-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-jenkins-single
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-trivy-cache-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-jenkins-single
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-sonar-cache-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-jenkins-single
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-venv-cache-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-jenkins-single
