apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: observability
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/filesystem-trim-daily: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn-storageclass
